(in-package #:goliga/tests)

(deftest (test-parse-rang :in goliga-tests) ()
  (is (goliga::rang= (goliga::parse-rang "3 kyu")
                     (goliga::parse-rang "3k")))
  (is (= (goliga::rang-int (goliga::parse-rang "1 Dan")) 0))
  (is (= (goliga::rang-int (goliga::parse-rang "3 dan")) 2))
  (is (= (goliga::rang-int (goliga::parse-rang "12kyu")) -12)))

(deftest (test-format-rang :in goliga-tests) ()
  (flet ((test (in out)
           (is (string= (goliga::format-rang (goliga::parse-rang in))
                        out))))
    (test "1d" "1 dan")
    (test "1k" "1 kyu")
    (test "12 kyu" "12 kyu")
    (test "9 Dan" "9 dan")
    (test "3 k" "3 kyu")))

(deftest (test-rang= :in goliga-tests) ()
  (is (goliga::rang= (goliga::parse-rang "3k")
                     (goliga::parse-rang "3 kyu")))
  (is (not (goliga::rang= (goliga::parse-rang "1 kyu")
                          (goliga::parse-rang "1 dan")))))
